---
title: Popularity of Google Search Results including "mmr" & "autism"  and Vaccination Coverage of the MMR Vaccine
---

<!-- VIDEO ON LOOP: see styles.css for formatting -->
<div class="video-wrapper">
  <video id="scaledvideo" controls preload="true" autoplay loop muted>
    <source src="https://drdavis.space/teaching/ds/sdd/media/2020/05/maniaci_final.mp4" >
  </video>
</div>


## Overview
The internet has the power to spread thoughts and ideas all over the world.
Whether this information is true or false, it can spread like wildfire.
Because of this, it is neccessary to observe whether the internet has had an effect on differing pieces of society.

One of the bigger issues circling the internet over the past decade has been whether or not to vaccinate children.
In 2007 Jenny McCarthy spoke out against vaccines when she was invited to talk on Oprah, stating that the Measles, Mumps, Rubella (MMR) Vaccine caused her child to develop autism [^NYTIMES].
However, since that point many academic journals have claimed otherwise.
In  2010 The Lancet retracted a major article published 12 years prior, which linked autism to the MMR Vaccine [^Lancet].
A study done in 2015 found no link betweeen the MMR Vaccine and Autism [^NLM].

It is likely that during the time each event occurred, a google search containing similar terms would produce the relevant article of that period.
By looking at the popularity of Google searches including the terms "MMR" and "Autism", we can see whether any of the events mentioned above have impacted vaccination coverage over time.

## Data Description
The data visualized above shows the behavior of two variables in relation to each other; MMR vaccination coverage and popularity of Google search terms.
Magnitude is not visualized.

The Google search term data was downloaded from Google Trends[^GTrends] and the vaccination coverage was downloaded from the Center for Disease Control (CDC).
The Google trends data was downloaded in 50 different CSVs, one for each state, and had monthly data, when yearly data was what needed to be compared.
A Python[^python] Script was used to average the monthly data for each year and reformat it into one CSV so it could be easily compared with the vaccination coverage data.
Once both data were in the same format percent change was calculated between each year using the following formula in excel[^Excel]: (x_2 - x_1)/|x_1| .
Zero was inputted as the no data value.
In order to avoid divide by zero errors, all zeros were replaced by 0.00000001.
Once this information was established, another python[^python] script was built to compare the behaviors of the 2 functions and sorted them on whether they were increasing, decreasing, or there was no change/no data available.
Because changing all the zeros to 0.00000001 would have caused the percent change formula to produce a huge number if this number was used as X_1, the script counted all these inputs as no data.

For each change in years, the data was visualized in QGIS[^qgis] using the same mapping properties and exported to png[^png] format.
The image files were loaded into GIMP[^gimp], optimized and exported as an animated GIF[^gif].
The animated gif was converted to a video using an ezgif[^ezgif] an online video converter.


<div class="credit-line">
Author: Gianna N. Maniaci.
Last edited: 2020-04-30.
</div>

[^NYTIMES]: New York Times. Online: https://www.nytimes.com/2014/04/22/opinion/bruni-autism-and-the-agitator.html
[^Lancet]: PubMed US National Library of Medicine National Institute of Health. Accessed 2020-04-15. Online: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2831678/
[^NLM]: PubMed US National Library of Medicine National Institute of Health. Accessed 2020-04-15. Online: https://www.ncbi.nlm.nih.gov/pubmed/25562790
[^GTrends]: Google Trends Data. Accessed 2020-04-15. Online: https://trends.google.com/trends/explore?date=all&geo=US&q=mmr%20autism
[^CDC]: Vaccination Coverage Data. Accessed 2020-04-15. Online: https://www.cdc.gov/vaccines/imz-managers/coverage/childvaxview/data-reports/mmr/trend/index.html
[^python]: Python. Copyright (C) 2001--2020. Python Software Foundation. Accessed 2020-04. Online: https://www.python.org/
[^Excel]: Microsoft Excel. Copyright (C) 2020. Accessed 2020-04. Online: https://www.microsoft.com/en-us/microsoft-365/excel
[^qgis]: QGIS. Software released through CC-BY-SA by the QGIS Development Team. Accessed 2020-04. Online: https://www.qgis.org
[^png]: Portable Network Graphics (PNG). Copyright 1995--2020 Greg Roelofs. Accessed 2020-04. Online: http://www.libpng.org/pub/png/
[^gimp]: GNU Image Manipulation Program (GIMP). Software released through CC-BY-SA by The GIMP Development Team. Accessed 2020-05-01. Online: https://www.gimp.org/
[^gif]: Graphics Interchange Format (GIF). Copyright 1987--1990 CompuServe. Accessed 2020-05-01. Online: https://www.w3.org/Graphics/GIF/spec-gif89a.txt
[^ezgif]: EZGIF. Accessed: 2020-05-01. Online: https://ezgif.com/gif-to-mp4/ezgif-4-f6774f2a7211.gif
