---
title: Spread of Land Development in Asia
---

<div class="video-wrapper">
  <video id="scaledvideo" controls preload="true" autoplay loop muted>
    <source src="https://drdavis.space/teaching/ds/sdd/media/2020/05/project_emmgillstrick.mp4" type="video/mp4" >
  </video>
</div>

## Overview
As the human population continues to grow exponentially we develop more and more natural land to build cities, factories, croplands, and numerous other man-made structures. Since 2001 the population in Asia alone has grown by more than a billion people, with 50% of people living in urban areas. It is important to be able to visualize this human impact on the natural world as we move towards a future where more and more resources and space will be necessary to keep up with the growing population. In the animation above we can see this human encroachment in Asia (with urban areas and cropland represented by red and green respectively) on undeveloped land (in white) throughout 2001-2018.

## Data Description
The data visualized above is the Land Cover Climate Modeling Grid collected by the Moderate Resolution Imaging Spectroradiometer (MODIS) sensor that is onboard the Terra[^terra] and Aqua[^aqua] satellites. Terra passes from north to south across the equator each morning, while Aqua passes south to north over the equator each afternoon. The data contains values representing different land cover types ranging from 0 to 16.

## Data Conversion Process
MODIS Land Cover Type data sets were downloaded in HDF[^hdf]format (specifically hdf4) from the Land Processes Distributed Active Archive Center ([LP DAAC](https://lpdaac.usgs.gov/products/mcd12c1v006/)) for each year from 2001-2018.
Each HDF4 file contained multiple subdatasets, data from "Majority_Land_Cover_Type_1" variable were extracted from each file and put into yearly raster files (.txt) in ASCII format with a computer program written in Python[^python] with the assistance of gdal[^gdal]. To better show urbanization and development of land, all undeveloped land cover types were reclassified as value 1, cropland as value 2, and urban land cover as 3. Water remained the same as 0.

For each raster file, the data was visualized in QGIS[^qgis] and exported to PNG[^png] image format. Each image was loaded into GIMP[^gimp], zoomed in onto Asia and exported as an animated GIF[^gif]. This GIF was then converted to a .mp4 using FFmpeg[^mpeg].

**Original Data Set Values:**

| Land Cover Type              | Raster Value |
| ---------------------------- | ------------ |
| Water                        | 0            |
| Evergreen Needleleaf Forest  | 1            |
| Evergreen Broadleaf Forest   | 2            |
| Deciduous Needleleaf Forest  | 3            |
| Deciduous Broadleaf Forest   | 4            |
| Mixed Forests                | 5            |
| Closed Shrublands            | 6            |
| Open Shrublands              | 7            |
| Woody Savannas               | 8            |
| Savannas                     | 9            |
| Grasslands                   | 10           |
| Permanent Wetlands           | 11           |
| Croplands                    | 12           |
| Urban and Built-up           | 13           |
| Natural Vegetation Mosaic    | 14           |
| Snow and Ice                 | 15           |
| Barren or Sparsely Vegetated | 16           |

**Modified Data Set Values:**

| Land Cover Type                | Raster Value |
| ------------------------------ | ------------ |
| Water                          | 0            |
| Undeveloped Land (1-11, 14-16) | 1            |
| Croplands                      | 2            |
| Urban and Built-up             | 3            |

<div class="credit-line">
Author: Emma Strickland.
Last edited: 2020-04-28
</div>

[^aqua]: About Aqua. Nasa.gov. Accessed 2020-04-28. Online: https://eospso.nasa.gov/missions/aqua
[^gdal]: Translator library for raster and vector geospatial data format. Online: https://gdal.org/
[^gif]: Graphics Interchange Format (GIF). Copyright 1987--1990 CompuServe. Online: https://www.w3.org/Graphics/GIF/spec-gif89a.txt
[^gimp]: GNU Image Manipulation Program (GIMP). Software released through CC-BY-SA by The GIMP Development Team. Online: https://www.gimp.org/
[^hdf]: Hierarchical Data Format. Copyright 2006--2019. The HDF Group. Online: https://www.hdfgroup.org/
[^mpeg]: Moving Picture Experts Group Standard 4 (MPEG-4). Online: https://mpeg.chiariglione.org/
[^png]: Portable Network Graphics (PNG). Copyright 1995--2019 Greg Roelofs. Online: http://www.libpng.org/pub/png/
[^python]: Python. Copyright (C) 2001--2019. Python Software Foundation. Online: https://www.python.org/
[^qgis]: QGIS. Software released through CC-BY-SA by the QGIS Development Team. Online: https://www.qgis.org
[^terra]: About Terra. NASA.gov. Online: https://terra.nasa.gov/about
