---
title: "Tornadoes Since the 1950s"
---

## Overview
The tornado is one of the most fascinating, destructive, and mysterious storm systems that occur in the United States. 
With data that only dates back to the 1950’s, long-term trends in the records are very difficult to identify, but it can be observed that the frequency of large-scale outbreaks are increasing. 
In fact, the number of tornadoes in the most extreme outbreak in a five-year interval doubled over the last half-century.

Tornadoes continue to mystify scientists on the exact conditions of their formation; atmospheric instability and wind shear are the building blocks for this fierce storm, but how these variables interact with our warming climate has led to many questions. 
Atmospheric instability occurs when warm, moist air is wedged under drier cooler air, and wind shear refers to the changes in wind direction and speed at different elevations in the atmosphere.

It is likely that a warmer, more humid world would lead to more frequent instability in the atmosphere, but a warmer climate could also lessen the chances for wind shear. 
Researchers have also found that the increase in outbreaks were driven by storm relative helicity, which is a measure of vertical wind shear. 
However, this factor has not been projected to increase under a warming climate, leaving us even more unsure regarding the correlation between a warming climate and increased tornado activity.

## Data Description
The data points visualized above were collected by the National Weather Service[^nws] field offices found in the Storm Data[^stormdata] publication. 
The storms are broken up in five year periods, starting in the year 1950 and ending in 2015. 

The initial data was in a comprehensive CSV file, and a script written in the Python[^python] programming language was used to group the data in five year increments and keep only those tornadoes recorded as a 3 or greater on the Fujita[^fujita] Scale. 

For each month, the data was visualized in ArcGIS Pro[^arcgis] using the same mapping properties and exported to PNG[^png] image format.
The image files were loaded into GIMP[^gimp], optimized and exported as an animated GIF[^gif].
The animated GIF was converted to a video using FFmpeg[^ffmpeg].

<div class="credit-line">
Author: Morgan E. Brickey.
Last edited: 2019-12-04
</div>

[^arcgis]: ArcGIS. Single Desktop GIS Application Part of Esri Geospatial Cloud. Accessed 2019-11-30.
Online: https://www.esri.com/en-us/arcgis/products/arcgis-pro/overview
[^ffmpeg]: FFmpeg is a trademark of Fabrice Bellard. Software released under GNU LGPL 2.1. Accessed 2019-11-30. Online: https://ffmpeg.org/
[^fujita]: Fujita Scale. Weather.gov. Accessed: 2019-11-30. Online: https://www.weather.gov/oun/efscale
[^gif]: Graphics Interchange Format (GIF). Copyright 1987--1990 CompuServe. Accessed 2019-11-30. 
Online: https://www.w3.org/Graphics/GIF/spec-gif89a.txt
[^gimp]: GNU Image Manipulation Program (GIMP). Software released through CC-BY-SA by The GIMP Development Team. Accessed 2019-11-30 Online: https://www.gimp.org/
[^nws]: National Weather Service. weather.gov. Accessed 2019-11-30.Online:  https://www.weather.gov
[^png]: Portable Network Graphics (PNG). Copyright 1995--2019 Greg Roelofs. Accessed 2019-11-30 
Online: http://www.libpng.org/pub/png/
[^python]: Python. Copyright (C) 2001–2019. Python Software Foundation. Accessed 2019-11-30. Online: https://www.python.org
[^stormdata]: Storm Data Publication. data.gov. Accessed 2019-11-30. Online: https://catalog.data.gov/dataset/storm-data-publication
