---
title: Encroachment of Humans Into Natural Areas
---

<!-- VIDEO ON LOOP: see styles.css for formatting -->
<div class="video-wrapper">
  <video id="oforiaddaevideo" controls preload="true" autoplay loop muted>
    <source src="https://drdavis.space/teaching/ds/sdd/media/2019/12/encroachment.mp4" type="video/mp4" >
  </video>
</div>

## Overview
The human population continues to exponentially grow, and it is estimated by 2020, the human population will be about 8 billion. As the population grows, so does the need for resources and the need for the population to expand into new areas to prevent overcrowding in cities and towns.

This expansion is sometimes also signified by the presence of poverty, as families and individuals search land for agriculture or look for fuel in the form of timber. As we live in an industrial age, this may be more common than we think.

As such, to measure the extent of human encroachment into natural areas, I decided to combine night time light data and land cover data, to measure the extent of human encroachment into natural areas.

I decided to examine this phenomenom on the continent of South America, particularly because it is where the Amazon Rainforest is, and I feel it would be a great proxy for the encroachment of humans into natural areas, since is is one of the most historically natural areas in the world

## Data Description
The data visualized above is a combination of normalized enhanced vegetation index (NDVI) and Defence Meteorological Satellite Program (DMSP) Operational Linescan System (OLS) nighttime lights data. The NDVI data was colleceted by the Vegetation Index and Phenology Lab (VIPPHEN)
NDVI ranges between -1 and 1. Negative values of NDVI (values approaching -1) correspond to water. Values close to zero (-0.1 to 0.1) generally correspond to barren areas of rock, sand, or snow. Low, positive values represent shrub and grassland (approximately 0.2 to 0.4), while high values indicate temperate and tropical rainforests (values approaching 1).

VIPPHEN NDVI data sets were downloaded in HDF[^hdf] from the Land Processes Distributed Active Archive Center ([LP DAAC](https://lpdaac.usgs.gov/)) for every 2 years starting from 1994.
The data were extracted using a computer program written in the Python[^python] programming language with the help of the scientific dataset application program interface provided by the [pyhdf](http://fhs.github.io/pyhdf/) package[^pyhdf].

For each year, the data were visualized in QGIS[^qgis] using the same mapping properties and exported to PNG[^png] image format.
The image files were loaded into GIMP[^gimp], optimized and exported as an animated GIF[^gif].
The animated GIF was converted to a video (encoded in MPEG-4[^mpeg4]) using FFmpeg[^ffmpeg].

<div class="credit-line">
Author: Yaw Ofori-Addae.
Last edited: 2019-12-18.
</div>

[^ffmpeg]: FFmpeg is a trademark of Fabrice Bellard. Software released under GNU LGPL 2.1. Accessed 2019-12-18. Online: https://ffmpeg.org/
[^gif]: Graphics Interchange Format (GIF). Copyright 1987--1990 CompuServe. Accessed 2019-12-18. Online: https://www.w3.org/Graphics/GIF/spec-gif89a.txt
[^gimp]: GNU Image Manipulation Program (GIMP). Software released through CC-BY-SA by The GIMP Development Team. Accessed 2019-12-18. Online: https://www.gimp.org/
[^hdf]: Hierarchical Data Format. Copyright 2006--2019. The HDF Group. Accessed 2019-12-18. Online: https://www.hdfgroup.org/
[^mpeg4]: Moving Picture Experts Group Standard 4 (MPEG-4). Standard developed by a working group of the International Organization for Standardization (ISO) and the International Electrotechnical Commission (IEC) joint technical committee. Accessed 2019-10-28. Online: https://mpeg.chiariglione.org/
[^png]: Portable Network Graphics (PNG). Copyright 1995--2019 Greg Roelofs. Accessed 2019-12-18. Online: http://www.libpng.org/pub/png/
[^pyhdf]: HDF - EOS Tools and Information Center. The HDF Group in collaboration with NASA's Earth Science Data and Information System (ESDIS) Project. Accessed 2019-10-28. Online: https://www.hdfeos.org/software/pyhdf.php
[^python]: Python. Copyright (C) 2001--2019. Python Software Foundation. Accessed 2019-12-18. Online: https://www.python.org/
[^qgis]: QGIS. Software released through CC-BY-SA by the QGIS Development Team. Accessed 2019-12-18. Online: https://www.qgis.org
