---
title: Arctic and Antarctic Sea Ice Over Time
author-meta: John Hennin
semester: Fall 2020
---

<!-- VIDEO ON LOOP: see styles.css for formatting -->
<div class="video-wrapper">
<style>
video {
  max-width: 100%;
  max-height: 100%;
}
</style>
  <video width=400 height=400 controls preload="true" autoplay loop muted>
    <source src="sea-ice-north2.mp4" type="video/mp4" >
  </video>
  <video width=400 height=400 controls preload="true" autoplay loop muted>
    <source src="sea-ice-south2.mp4" type="video/mp4" >
  </video>
</div>

> *"Ice, ice, baby."* -- Vanilla Ice

## Overview
Too many people utilize an "out of sight, out of mind" approach when it comes to the gradually diminishing sea ice of the North (left animation) and South (right animation) Poles.
These people may either reason that melting sea ice just isn't as calamitous as others believe it to be or they deny that the Earth's sea ice is melting at all.
For those that fall in the latter category, it's crucial to understand sea ice for what it is: Earth's natural reflector.

Sea ice has a naturally reflective surface, so it reflects most of the significant amount of sunlight that reaches it.
This prevents the polar regions from absorbing much sunlight and, consequently, keeps them cold.
This also means that even if the sea ice melts a seemingly ineffectual amount, the polar regions will absorb much more sunlight.[^noaa]
The aforementioned process will evolve into a cycle of warming and melting, creating great disruptions in our climate.
According to the National Snow and Ice Data Center (NSIDC), "Even a small increase in temperature can lead to greater warming over time, making the polar regions the most sensitive areas to climate change on Earth.[^nsidcseaicequote]"

In order to demonstrate that the Earth's sea ice is, in fact, significantly diminishing, it's important that the deniers, along with everyone else, are presented with clear, indeniable evidence.
The animations above both demonstrate that sea ice is melting, but, notably, at greatly different rates depending on the polar region.
The 5 year percent changes are given in the animations, but the 40 year percent changes (from 1980 to 2020) are roughly -27 percent for the North Pole and only -0.4 percent for the South Pole.

## Data Description
The raster data used in the animations above was provided by the NSIDC[^nsidcdata] at https://nsidc.org/data/G02135/versions/3, originally in GeoTIFF[^geotiff] format.
The data describes the sea ice extent or "the expanse covered by ice at greater than 15 percent monthly mean concentration[^nsidcdataquote]" in the Arctic and Antarctic for every 5 years from July, 1980 to July, 2020.
This means that each cell in white depicts a 25km by 25km area that was at least 15% sea ice (on average for July of that year).

Using the Python[^python] programming language and the package rasterio[^rasterio], the GeoTIFFs were converted to ASCII raster files to allow for easier future manipulation and analysis.
To preserve the Coordinate Reference System information in each GeoTIFF, the script pulled the relevant information from the file and reproduced it in a supplementary PRJ file.
The script also produced a text file describing the amount of cells in each raster file that belonged to a unique value.
In this case, since every cell that contained at least 15% sea ice was given the same value of 1, the percent change of sea ice between certain years could be easily calculated using the count provided by the text file.

For each year that was downloaded, the data was visualized and colored (so green represented land, white represented sea ice, and blue represented sea water) using QGIS[^qgis] and each raster was exported to the PNG[^png] format.
The images pulled from QGIS were then made into two GIFs[^gif] (one for the Arctic and one for the Antarctic) using GIMP[^gimp] and the GIFs were converted to the MPEG-4[^mpeg4] format using FFmpeg[^ffmpeg].

<div class="credit-line">
Author: John Hennin.
Last edited: 2020-11-16.
</div>

[^noaa]: US Department of Commerce, National Oceanic and Atmospheric Administration. “How Does Sea Ice Affect Global Climate?” Accessed 2020-11-10. https://oceanservice.noaa.gov/facts/sea-ice-climate.html.
[^nsidcseaicequote]: “All About Sea Ice | National Snow and Ice Data Center.” Accessed 2020-11-10. https://nsidc.org/cryosphere/seaice/index.html.
[^nsidcdata]: Fetterer, F., K. Knowles, W. N. Meier, M. Savoie, and A. K. Windnagel. 2017, updated daily. Sea Ice Index, Version 3. Monthly Mean Extent. Boulder, Colorado USA. NSIDC: National Snow and Ice Data Center. doi: https://doi.org/10.7265/N5K072F8. Accessed 2020-10-26.
[^geotiff]: Geostationary Earth Orbit Tagged Image File Format (GeoTIFF). Accessed 2020-11-05. Online: https://earthdata.nasa.gov/esdis/eso/standards-and-references/geotiff
[^nsidcdataquote]: Windnagel, A. “Sea Ice Index.” October 2008. PDF file. Accessed 2020-11-04. Online: https://nsidc.org/data/G02135/versions/3?qt-data_set_tabs=3#qt-data_set_tabs
[^python]: Python. Copyright (C) 2001--2019. Python Software Foundation. Accessed 2020-11-05. Online: https://www.python.org/
[^rasterio]: Rasterio. Copyright (c) 2013. Mapbox. Accessed 2020-11-05. Online: https://github.com/mapbox/rasterio
[^qgis]: Quantum Geographic Information System (QGIS). Software released through CC-BY-SA by the QGIS Development Team. Accessed 2020-11-05. Online: https://www.qgis.org
[^png]: Portable Network Graphics (PNG). Copyright 1995--2019 Greg Roelofs. Accessed 2020-11-05. Online: http://www.libpng.org/pub/png/
[^gif]: Graphics Interchange Format (GIF). Copyright 1987--1990 CompuServe. Accessed 2020-11-05. Online: https://www.w3.org/Graphics/GIF/spec-gif89a.txt
[^gimp]: GNU Image Manipulation Program (GIMP). Software released through CC-BY-SA by The GIMP Development Team. Accessed 2020-11-05. Online: https://www.gimp.org/
[^mpeg4]: Moving Picture Experts Group Standard 4 (MPEG-4). Standard developed by a working group of the International Organization for Standardization (ISO) and the International Electrotechnical Commission (IEC) joint technical committee. Accessed 2020-11-05. Online: https://mpeg.chiariglione.org/
[^ffmpeg]: FFmpeg is a trademark of Fabrice Bellard. Software released under GNU LGPL 2.1. Accessed 2020-11-05. Online: https://ffmpeg.org/
