---
title: "Moving (Not Sitting) Ducks"
author-meta: Brian Wu
semester: Fall 2020
---

<div class="video-wrapper">
  <video class="video-4x4mw" controls preloaded="true" autoplay loop muted>
    <source src="https://drdavis.space/teaching/ds/sdd/media/2020/11/duck_movement.mp4">
  </video>
</div>
## Project Description
During self-quarantine, I picked up a new hobby: bird-watching. Since then, my interest in birds has dramatically increased, which is exactly why I decided to find a data set about birds. Over the past few months, I noticed that some birds that usually came to my bird feeders suddenly vanished. I soon learned that this was because some birds migrated due to changes in the seasons, while others did not. This is why I decided to find a dataset that keeps track of bird movement, which will help determine whether a certain species of birds follows a specific migration pattern. 

In this project, I found a CSV file on Pacific Sea Duck Migration, copied bits of it into a new CSV file using Python[^python], and visualized it using QGIS[^qgis]. By looking at the animation I created, it is safe to say that pacific sea ducks migrate from Southern British Columbia to northern Canada every spring. 

## Data Description and Process
The csv data file that contains the specific locations of the individual birds came from MoveBank.org[^movebank], which is an online database for animal tracking data.
I created my animation by following a procedure done by a jouranlist named Anita Graser[^agraser]. This involved adding a CSV file to QGIS as a Delimited Text Layer and running TimeManager to create a visualization. I tested out the original csv file that I found and decided to perform the visualization procedure on it. However, the visualization turned out to be very messy, because it contained too many visual data points, and QGIS crashed as a result. This is why I decided to write a Python script to obtain information on only 20 individual ducks (identified by distinct tag numbers). The information that I obtained included the Time Stamp (date where data was recorded), longitude location, latitude location, and the specific tag numbers of each individual duck. I also decided to only obtain data that was collected on May 2014 to simply the data visualization process. 

To visualize this data, I started by adding the original CSV file into my QGIS project as a delimited text layer and configured Time Manager. Then, I exported the animation video and converted it into a gif using EXGIF[^ezgif].


<div class="credit-line">
Author: Brian Wu.
Last Edited: 2020-11-20
</div>

## References

[^agraser]: Graser, Anita. "How to visualize bird migration data with QGIS TimeManager". Accessed 2020-11-08. Online: https://anitagraser.com/2016/09/24/how-to-visualize-bird-migration-data-with-qgis-timemanager/

[^qgis]: QGIS. Software released through CC-BY-SA by the QGIS Development Team. Accessed 2020-11-10. Online: https://www.qgis.org/en/site/

[^movebank]: Wikelski M, Davidson SC, Kays R [year]. Movebank: archive, analysis and sharing of animal movement data. Hosted by the Max Planck Institute of Animal Behavior. www.movebank.org, Accessed on 2020-11-01. Online: https://www.movebank.org/cms/movebank-content/about-movebank

[^python]: Python. Copyright (C) 2001–2019. Python Software Foundation. Accessed 2020-11-01. Online: https://www.python.org/

[^ezgif]: EZGIF. Accessed 2020-11-15. Online: https://ezgif.com/maker
