---
title: "Resources | Data"
output:
  html_document:
    includes:
      in_header: searchjs.html
      after_body: footer.html
---

***

<!--
      Search bar
                      -->
<div class="search-bar" style="border:1px solid #DDD; width:396px; margin-bottom:15px;">
<p style="margin:5px;">
<i class="icon fa fa-search"></i>
<input type="text" id="myInput" onkeyup="updateSheet()" placeholder="Search..." style="border:none; padding:0; width:365px;">
</p>
</div>

<!--
      Definition List
                        -->

[500 Cities Project](https://www.cdc.gov/500cities/)
:   Provides city- and census tract-level small area estimates for chronic disease risk factors, health outcomes, and clinical preventive service use for the largest 500 cities in the United States.
    Includes an interactive map and data portal.

[Alaska Hydrography Database](http://akhydro.uaa.alaska.edu/)
:   Provides updated hydrography (surface water such as streams, rivers and watershed areas) data that meet statewide and national standards.

[American Panorama](https://dsl.richmond.edu/panorama/)
:   A historical atlas of the United States for the twenty-first century combining cutting-edge research with innovative interactive mapping techniques, designed to appeal to anyone with an interest in American history or a love of maps.

[ArcGIS Living Atlas - Indicators of the Planet](https://experience.arcgis.com/experience/003f05cc447b46dc8818640c38b69b83/)
:   See the latest in global issues with links to their respective open data portals.

[ASTER Volcano Archive](https://ava.jpl.nasa.gov/)
:   The world's largest specialty archive of volcano data, including publicly available high-resolution multispectral ASTER data.

[Climate Data Online Search](https://www.ncdc.noaa.gov/cdo-web/search)
:   Find past weather and climate data provided by NOAA's National Centers for Environmental Information (NCDC).

[Copernicus Land Monitoring Service](https://land.copernicus.eu/)
:   [Copernicus](https://www.copernicus.eu/en) is the European Union's Earth observation programme that draws from satellite and in-situ (non-space) data.
    Information from this programme is provided through six thematic services: land, marine, atmosphere, climate change, emergency management and security.
    All information is free and openly accessible to all users.
    The Land Monitoring Service provides access to bio-geophysical products, land cover and land use, environmental hotspots, and satellite imagery.

[Data.gov](https://www.data.gov/)
:   The home of the U.S. Government's open data.

[Data.gov.uk](https://data.gov.uk/)
:   UK's Find Open Data service providing data published by central government, local authorities and public bodies with links to download data files.

[Defra Data Services Platform](https://environment.data.gov.uk/)
:   The Department for Environment, Food & Rural Affairs make environmental data (e.g., LIDAR, photography, bathymetry, multispectral) openly available to a wide range of users available for download in commonly used formats.
    Click "Surveys" in the menu at the top to open a web-based mapping interface.

[Earth Engine Data Catalog](https://developers.google.com/earth-engine/datasets/catalog)
:   Public data catalog that includes a variety of standard Earth science raster datasets.

[EarthData](https://search.earthdata.nasa.gov/search)
:   Access thousands of unique data products in NASA's Earth Observing System Data and Information System (EOSDIS) collection from a variety of sources including the International Space Station, satellites, airborne campaigns, field campaigns, in-situ instruments, and model outputs.

[EarthExplorer](https://earthexplorer.usgs.gov/)
:   An online search, discovery, and ordering tool developed by the United States Geological Survey (USGS) that supports the searching of satellite, aircraft, and other remote sensing inventories through interactive and textual-based queries.

[EarthStat](http://www.earthstat.org/)
:   Cutting-edge data on the global food system to help others make science-based decisions.

[EarthWorks](https://earthworks.stanford.edu/)
:   Search, download, and explore geospatial data shared across a multi-academic consortium.

[Elfelt Server List](https://mappingsupport.com/p/surf_gis/list-federal-state-county-city-GIS-servers.pdf)
:   (PDF) list of 50+ federal, 150+ state, 200+ county, and 200+ city GIS servers in the United States.

[European Commission Joint Research Centre - ESDAC](https://esdac.jrc.ec.europa.eu/themes/landslides)
:   European landslide inventory.

[Facebook Data for Good](https://dataforgood.fb.com/)
:   Using data to address some of the world's greatest humanitarian issues.

[FAO GeoNetwork](http://www.fao.org/geonetwork/srv/en/main.home)
:   Provides interactive maps, satellite imagery and related spatial databases for sustainable development and decision making in agriculture, forestry, fisheries and food security.

[FEC Elections and Voting](https://www.fec.gov/introduction-campaign-finance/election-and-voting-information/)
:   Every two years, the Federal Election Commission publishes Federal Elections, a compilation of official, certified federal election results; these include primary, runoff, and general election results for the Senate, the House of Representatives and (when applicable) the President.

[Fuzzy Gazeteer](http://isodp.hof-university.de/fuzzyg/query/)
:   Name search for feature locations from all over the world.

[GADM maps and data](https://gadm.org/)
:   Provides maps and spatial data for all countries and their sub-divisions, including over 300,000 administrative areas in vector format.

[geoBoundaries](https://www.geoboundaries.org/)
:   The world's largest open, free and research-ready database of political administrative boundaries.

[GeoPlatform](https://www.geoplatform.gov/)
:   Using collaboration, common data, services, applications and shared infrastructure to address national and regional issues and priorities (The Federal Geographic Data Committee).

[GeoQuery](http://geo.aiddata.org/query/#!/)
:   Enables individuals and organizations of all skill levels to freely find and aggregate satellite, economic, health, conflict, and other spatial data into a single, simple-to-use file compatible with Microsoft Excel and other common software ([Goodman et al., 2019](https://doi.org/10.1016/j.cageo.2018.10.009)).

[Global Dataset of Historic Yield](https://doi.pangaea.de/10.1594/PANGAEA.909132)
:   Offers annual time series data of 0.5-degree grid-cell yield estimates of major crops worldwide for the period 1981-2016.

[Global Forest Watch](https://data.globalforestwatch.org/)
:   Committed to providing the highest-quality data on the world's forests.

[Global Shoreline Dataset](https://dnc.nga.mil/PrototypeGSD.php)
:   The NGA Office of Global Navigation, Maritime Domain is in the process of developing a new version of World Vector Shoreline (WVS) and in support of this effort has acquired a satellite-derived Global Shoreline Data set.
    This new Global Shoreline Data (GSD) set is an approximation of the High Water Line; it is NOT a Mean High Water Line.
    Continuous shoreline data, approximately between 60 degrees north and 56 degrees south, are being made available.

[Google Dataset Search](https://toolbox.google.com/datasetsearch)
:   Find datasets stored hosted in thousands of repositories across the Web through simple keyword search.

[Google Public Data Directory](https://www.google.com/publicdata/directory)
:   A repository for public data.
    Quickly retrieve geographic coordinates for world countries ([countries.csv](https://developers.google.com/public-data/docs/canonical/countries_csv)) and US states ([states.csv](https://developers.google.com/public-data/docs/canonical/states_csv)).

[Harmonized World Soil Database v 1.2](https://webarchive.iiasa.ac.at/Research/LUC/External-World-soil-database/HTML/)
:   Global elevation, slope, and aspect data in 5 min and 30 arc second resolutions.

[Homeland Infrastructure Foundation-Level Data (HIFLD)](https://hifld-geoplatform.opendata.arcgis.com/)
:   This site provides national foundation-level geospatial data within the open public domain that can be useful to support community preparedness, resiliency, research, and more.
    The data is available for download as CSV, KML, Shapefile, and accessible via web services to support application development and data visualization.

[Humanitarian Data Exchange (HDX)](https://data.humdata.org/)
:   Find, share and use humanitarian data all in one place.

[International Best Track Archive for Climate Stewardship (IBTrACS)](https://www.ncdc.noaa.gov/ibtracs/)
:   Tropical cyclone (TC) best track data already exist as individual storm tracks at other agencies and IBTrACS merges these data sets into a worldwide TC database available in netCDF, CSV, and shapefile formats.

[International IDEA](https://www.idea.int/)
:   The International Institute for Democracy and Electoral Assistance is an intergovernmental organization that works to support and strengthen democratic institutions and processes around the world, to develop sustainable, effective and legitimate democracies.
    Browse their databases, which focus on three main impact areas: electoral processes, constitution-building, political participation and representation.
    They also address issues of gender, diversity, and conflict and security.

[ISRIC SOTER Database](https://www.isric.org/projects/soil-and-terrain-soter-database-programme)
:   Soil and terrain maps for South America, Africa (parts), Europe (parts), and Asia (parts) from 1986 to 2016.

[Kaggle](https://www.kaggle.com/datasets)
:   Explore, analyze, and share quality data in an accessible, non-proprietary format where each dataset is a community where you can discuss data, discover public code and techniques, and create your own projects.

[knoema](https://knoema.com/)
:   Free data, statistics, analysis, visualization and sharing.

[List of GIS data sources](https://en.wikipedia.org/wiki/List_of_GIS_data_sources)
:   Wikipedia guide of GIS data sources (including some geoportals) that provide information that can be used in GIS and spatial databases for purposes of geospatial analysis and cartographic mapping.

[Mapping Inequality](https://dsl.richmond.edu/panorama/redlining/)
:   The Home Owners' Loan Corporation (HOLC), between 1935 and 1940, created thousands of area descriptions using data and evaluations organized by local real estate professionals, such that, in each city, grades could be assigned to residential neighborhoods that reflect their "mortgage security" that would then be visualized on color-coded maps.
    These data, under CC-BY-NC-SA, are now available to download in GIS data formats (e.g., Shapefile, GeoJSON, and imagery).

[Movebank](https://www.movebank.org/cms/movebank-main)
:   Hosted by the Max Planck Institute of Animal Behavior in coordination with the North Carolina Museum of Natural Sciences, the Ohio State University and the University of Konstanz, Movebank is a free online platform that helps researchers manage, share, analyze and archive animal movement data.

[National Land Cover Database (NLDC)](https://www.mrlc.gov/index.php)
:   Provides spatial reference and descriptive data for characteristics of the land surface such as thematic class (for example, urban, agriculture, and forest), percent impervious surface, and percent tree canopy cover.

[Natural Earth](http://www.naturalearthdata.com/)
:   A public domain map dataset featuring vector and raster data.

[Open Data Inception](https://opendatainception.io/#)
:   An interactive map of 2k+ open data portals from around the world.
    Opendatasoft's mission is to support organizations by helping people access data and make sense of it and they offer market-leading data sharing solutions that allow you to easily publish, manage, combine, analyze, visualize, and share data in a variety of formats on a single platform.

[OpenTopography](https://opentopography.org/)
:   OpenTopography aims to democratize access to high-resolution topographic data in a manner that serves users with varied expertise, application domains, and computing resources.

[PRISM Climate Group](https://www.prism.oregonstate.edu/)
:   A gathering of climate observations from a wide range of monitoring networks available at multiple spatial/temporal resolutions, covering the period from 1895 to the present.

[Global Shark Attack File](http://www.sharkattackfile.net/)
:   A time-stamped semi-geolocated incident log of global shark attacks.

[Socioeconomic Data and Applications Center (sedac)](https://sedac.ciesin.columbia.edu/)
:   One of the Distributed Active Archive Centers (DAACs) in the Earth Observing System Data and Information System (EOSDIS) that focuses on human interactions in the environment.
    _Requires an EARTHDATA account._
    _Registration is free._

[SRTM 30-m DEM](http://dwtkns.com/srtm30m/)
:   Derek Watkins's interactive map for easily downloading Shuttle Radar Topography Mission (SRTM) thirty meter (30 m) resolution elevation tiles from NASA servers.

[TanDEM-X Science Server](https://tandemx-science.dlr.de/)
:   Global 12, 30, and 90 m digital elevation models.

[Thematic Mapping World Borders](http://thematicmapping.org/downloads/world_borders.php)
:   Esri shapefile of the world's country borders in two resolutions.
    CC BY-SA 3.0 by [Bj&oslash;rn Sandvik](https://thematicmapping.org/) 2009.

[TopoView](https://ngmdb.usgs.gov/topoview/)
:   A digital repository of USGS 1:250,000 scale and larger (more detailed) maps printed between 1884 (the inception of the topographic mapping program) and 2006.

[US Census Bureau](https://data.census.gov/cedsci)
:   The leading source of quality data about the US's people and economy.

[USDA Web Soil Survey](https://websoilsurvey.sc.egov.usda.gov/App/HomePage.htm)
:   Soil data for the US and its territories.

[USGS Continents](https://pubs.usgs.gov/of/2006/1187/basemaps/continents/)
:   Esri shapefile for the major continent boundaries provided from the Archival Policies and Collections Database for the Woods Hole Science Center's Marine Sediment Samples: U.S. Geological Survey Open-File Report 2006-1187, version 1.0 ([Buczkowski & Kelsey, 2007](http://pubs.usgs.gov/of/2006/1187/)).

[USGS The National Map](https://www.usgs.gov/core-science-systems/ngp/tnm-delivery/)
:   GIS data download and visualization services provided by the U.S. Geological Survey.

[Virginia GIS Clearinghouse](https://vgin.maps.arcgis.com/home/index.html)
:   A repository of geospatial data produced and used by state agencies in Virginia (see Virginia Geospatial Clearinghouse Nodes for open data portals of every available county or municipality in VA).

[World Vector Shoreline](https://shoreline.noaa.gov/data/datasheets/wvs.html)
:   The original World Vector Shoreline (WVS) was a digital data file containing the shorelines, international boundaries, and country names of the world.
    WVS data were processed into the National Geospatial-Intelligence Agency (NGA) Vector Product Format in 1995, resulting in the highest resolution demarcation of coastline globally available, the World Vector Shoreline Plus (now a pay-for service).
    A free and easy-to-use interface is available for the Global Shoreline Dataset (GSD) at the NGA's website: https://dnc.nga.mil/PrototypeGSD.php.
